version: "3.8"

services:
  db:
    image: mysql:8.0.37
    container_name: mysql-escuela-nieve
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: "123456789"
      MYSQL_DATABASE: escuelaDeportesNieve
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./Backend
    container_name: backend-escuela-nieve
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: "123456789"
      DB_NAME: escuelaDeportesNieve
    ports:
      - "5001:5001"
    depends_on:
      - db

  frontend:
    build: ./FrontEnd
    container_name: frontend-escuela-nieve
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mysql_data:
